config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:edit, :update, :destroy, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(form_params)
    if @post.save
      redirect_to posts_path, notice: 'created'
      redirect_to posts_path, { :notice => 'created' }
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(form_params)
      redirect_to posts_path, notice: 'updated'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def form_params
    params.require(:post).permit(:title, :content)
  end

  def find_post
    @post = Post.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgirls</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <p style="color: red;"><%= flash[:notice] %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_post_form.html.erb
<%= form_for @post do |f| %>
  <%= @post.errors.full_messages %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'posts/post_form' %>

app/views/posts/index.html.slim
h1.head#id Posts

- @posts.each do |post|
  h2= link_to post.title, post_path(post)
  p= link_to 'Edit', edit_post_path(post)
  p= link_to 'Destroy', post_path(post), method: :delete

= link_to 'New Post', new_post_path

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'posts/post_form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.content %></p>